zuul:
  routes:
    oauth:
      path: /oauth/**
      url: http://localhost:8081/spring-security-oauth-server/oauth
    resource:
      path: /foos/**
      url: http://localhost:8082/spring-security-oauth-resource/foos/